title: One Mind, Two Stars Wiki
markdown: kramdown
theme: minima
baseurl: "/One-Mind-Two-Stars-Wiki"

collections:
  characters:
    output: true
    permalink: /characters/:name.html

defaults:
  - scope:
      path: ""
      type: characters
    values:
      layout: default
